# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02caeaa4a0f9a9bd9078c161ebb0aace60ca1c3328718e8d9d805770c4d5c012314787dd8569c0b7b0db20f60bd798e5260a5f20d3bf08d944a9400a92ec27f3

test:
  secret_key_base: ff6919cad467ba8911e70ba17e49ea70b628c96020b1cbff0aa4fd7f86e54764c58e05071380809b6724647e6449aade3bf0630f6a2128846d226db2873a1e93

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
